// FILE: lib/firebase_options.dart
// ============================================================
// ACTION REQUIRED: Replace this file with the one generated by
// running: flutterfire configure
// in your project root after setting up your Firebase project.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  // TODO: Replace with your actual Firebase config from flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAk9DOEc_hmyeAJEob8QBAyQkiZCp_CPuI",
      authDomain: "uberzo.firebaseapp.com",
      databaseURL: "https://uberzo-default-rtdb.firebaseio.com",
      projectId: "uberzo",
      storageBucket: "uberzo.firebasestorage.app",
      messagingSenderId: "805708188196",
      appId: "1:805708188196:web:4bbfbf0b2833ade319a6b1",
      measurementId: "G-9F656XRL64"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.yourcompany.dropshipapp',
  );
}
